name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    
    steps:
    - uses: actions/checkout@v3
    - name: prepare apt
      run:  apt update && apt full-upgrade -y
    - name: dependencies
      run: |
        git clone https://github.com/freetype/freetype2.git .
        cp -r freetype2/include/ .
        make
    - name: make
      run: make

    - uses: actions/upload-artifact@master
      with:
        name: damnthing
        path: build
