name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    
    steps:
    - uses: actions/checkout@v3
    - name: prepare apt
      run:  apt update && apt full-upgrade -y
    - name: dependencies
      run: |
        apt install *free*type* -y
        apt full-upgrade
        git clone --recursive https://github.com/freetype/freetype.git
        cd freetype
        make install
    - name: make
      run: make

    - uses: actions/upload-artifact@master
      with:
        name: damnthing
        path: build
