name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    
    steps:
    - uses: actions/checkout@v3
    - name: prepare apt
      run:  apt update && apt full-upgrade -y
    - name: dependencies
      run: |
        dpkg --add-architecture ppc // not native for amd64 (ibm)
        dpkg --add-architecture arm64 // not native for amd64 (nintendo)
        dpkg --add-architecture aarach64 // same as above with dif software impl (apple???)
        dpkg --add-architecture i386 // intel's 64/32bit(canruneither??imamdusersodno) bullshit soso imo
        cd freetype
        make
    - name: make
      run: make

    - uses: actions/upload-artifact@master
      with:
        name: damnthing
        path: build
