name: release as action

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    
    steps:
    - uses: actions/checkout@v3
    - name: prepare apt
      run:  apt update && apt full-upgrade -y
    - name: dependencies
      run: |
        echo start; echo nah && mkdir include; echo wiiheehii
        
        git clone https://github.com/freetype/freetype.git 
        cp -r freetype/include/* include/

        cp freetype/include/ft2build.h .
        cp ft2build.h source/
        mkdir source
        cp -r include source
        
        make
    - name: make
      run: make

    - uses: actions/upload-artifact@master
      with:
        name: damnthing
        path: build
