name: zzzzzzzzzzzz

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    
    steps:
    - uses: actions/checkout@v3
    - name: prepare apt
      run:  apt update && apt full-upgrade -y
    - name: dependencies
      run: |
        export CC=powerpc-eabi-gcc
      
        echo start; echo nah && mkdir include; echo wiiheehii
        
        git clone https://github.com/wtfloltk/freetype.git ilost
        cd ilost
        mkdir fmlkillmoi
        cd fmlkillmoi
        cmake ../
        make
        make install
        echo makeinstallyallfoolsforshureifyourelikemii
        cd ..
        cp -r freetype/include/* include/

        cp freetype/include/ft2build.h .
        cp ft2build.h source/
        cp -r include source

        mkdir new
        cd new
        cp -r ../source/* .
        cp -r include/* .
        cp -r include/freetype/* .
        cp -r ../source/* .

        cp ../Makefile .
    - name: make
      run: |
        cd new; make

    - uses: actions/upload-artifact@master
      with:
        name: damnthing
        path: new/build
