name: zzzzzzzzzzzz

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    
    steps:
    - uses: actions/checkout@v3
    - name: prepare apt
      run:  apt update && apt full-upgrade -y
    - name: dependencies
      run: |
        export CC=powerpc-eabi-gcc
        cd libs
        make clean
        make
        cd ..
        cd source
        cd mplayer
        make clean
        make
        cd ..
        make clean 
        make
        
    - name: make
      run: |
        make

    - uses: actions/upload-artifact@master
      with:
        name: damnthing
        path: build
